"""user_products_added

Revision ID: 68cda2a32929
Revises: db978c26df5a
Create Date: 2023-08-27 20:49:21.661179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68cda2a32929"
down_revision = "db978c26df5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("special_name", sa.String(), nullable=True),
        sa.Column("like", sa.Boolean(), nullable=True),
        sa.Column("recommend", sa.Boolean(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_product_id"), "user_product", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_product_id"), table_name="user_product")
    op.drop_table("user_product")
    # ### end Alembic commands ###
