"""eat_lists_added

Revision ID: db978c26df5a
Revises: ed75112d232e
Create Date: 2023-08-26 14:45:07.979959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db978c26df5a"
down_revision = "ed75112d232e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eat_list",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_eat_list_id"), "eat_list", ["id"], unique=False)
    op.create_table(
        "eat_list_product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("eat_list_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["eat_list_id"],
            ["eat_list.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eat_list_product_id"), "eat_list_product", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_eat_list_product_id"), table_name="eat_list_product")
    op.drop_table("eat_list_product")
    op.drop_index(op.f("ix_eat_list_id"), table_name="eat_list")
    op.drop_table("eat_list")
    # ### end Alembic commands ###
