"""add_count_eatListProduct

Revision ID: a0c70229dfcf
Revises: 68cda2a32929
Create Date: 2023-08-29 08:27:48.944713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0c70229dfcf"
down_revision = "68cda2a32929"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("eat_list_product", sa.Column("count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("eat_list_product", "count")
    # ### end Alembic commands ###
