"""added_user_info

Revision ID: eee48a76fac5
Revises: a0c70229dfcf
Create Date: 2023-08-30 07:43:54.323052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eee48a76fac5"
down_revision = "a0c70229dfcf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("activity", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_user_info_id"), "user_info", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_info_id"), table_name="user_info")
    op.drop_table("user_info")
    # ### end Alembic commands ###
