"""products_added

Revision ID: ed75112d232e
Revises: ef1f0a488085
Create Date: 2023-08-26 11:44:23.713936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed75112d232e"
down_revision = "ef1f0a488085"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quote", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_currency_id"), "currency", ["id"], unique=False)
    op.create_table(
        "product_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_source_id"), "product_source", ["id"], unique=False
    )
    op.create_table(
        "product_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_type_id"), "product_type", ["id"], unique=False)
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("total_fat", sa.Integer(), nullable=True),
        sa.Column("total_carb", sa.Integer(), nullable=True),
        sa.Column("total_protein", sa.Integer(), nullable=True),
        sa.Column("vitamin_d", sa.Integer(), nullable=True),
        sa.Column("calcium", sa.Integer(), nullable=True),
        sa.Column("iron", sa.Integer(), nullable=True),
        sa.Column("potassium", sa.Integer(), nullable=True),
        sa.Column("available", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currency.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["product_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["product_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_id"), "product", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_id"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_product_type_id"), table_name="product_type")
    op.drop_table("product_type")
    op.drop_index(op.f("ix_product_source_id"), table_name="product_source")
    op.drop_table("product_source")
    op.drop_index(op.f("ix_currency_id"), table_name="currency")
    op.drop_table("currency")
    # ### end Alembic commands ###
